# Generated by Django 4.1.9 on 2023-05-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_sistemenacbzdvemaspremenljivkama'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemEnacbSTremiSpremenljivkami',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('najmanjsa_vrednost', models.SmallIntegerField(default=-19, help_text='Najmanjša možna vrednost koeficienta in rešitve', verbose_name='najmanjša vrednost')),
                ('najvecja_vrednost', models.SmallIntegerField(default=19, help_text='Največja možna vrednost koeficienta in rešitve', verbose_name='največja vrednost')),
            ],
            options={
                'verbose_name': 'Sistemi enačb / iskanje rešitve sistema linearnih enačb s tremi spremenljivkami',
            },
            bases=('problems.problem',),
        ),
        migrations.AlterModelOptions(
            name='sistemenacbzdvemaspremenljivkama',
            options={'verbose_name': 'Sistemi enačb / iskanje rešitve sistema linearnih enačb z dvema spremenljivkama'},
        ),
        migrations.RemoveField(
            model_name='sistemenacbzdvemaspremenljivkama',
            name='maksimalna_vrednost',
        ),
        migrations.RemoveField(
            model_name='sistemenacbzdvemaspremenljivkama',
            name='minimalna_vrednost',
        ),
        migrations.AddField(
            model_name='sistemenacbzdvemaspremenljivkama',
            name='najmanjsa_vrednost',
            field=models.SmallIntegerField(default=-19, help_text='Najmanjša možna vrednost koeficienta v enačbi', verbose_name='najmanjša vrednost'),
        ),
        migrations.AddField(
            model_name='sistemenacbzdvemaspremenljivkama',
            name='najvecja_vrednost',
            field=models.SmallIntegerField(default=19, help_text='Največja možna vrednost koeficienta v enačbi', verbose_name='največja vrednost'),
        ),
    ]
